[build]
target = "i586-unknown-none.json"

[target.i586-unknown-none]
rustflags = [
    "-Clink-args=--image-base=0x10000",
    "-Crelocation-model=static",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
