[build]
target = "x86_64-unknown-none.json"

rustflags = [
    "-Clink-args=--image-base=0xffffffff80000000",
    "-Ccode-model=kernel",
    "-Crelocation-model=static",

    "-Ctarget-feature=+sse",
    "-Ctarget-feature=+sse2",
    "-Ctarget-feature=+sse3",
    "-Ctarget-feature=+ssse3",
    "-Ctarget-feature=+sse4.1",
    "-Ctarget-feature=+sse4.2",
    "-Ctarget-feature=+avx",
    "-Ctarget-feature=+avx2",
    "-Ctarget-feature=+fma",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
