[build]
target = "x86_64-unknown-none.json"

rustflags = [
    "-C", "link-args=-image-base=0x1400000000",

    "-Ctarget-feature=+mmx",
    "-Ctarget-feature=+sse",
    "-Ctarget-feature=+sse2",
    "-Ctarget-feature=+sse3",
    "-Ctarget-feature=+ssse3",
    "-Ctarget-feature=+sse4.1",
    "-Ctarget-feature=+sse4.2",
    "-Ctarget-feature=+avx",
    "-Ctarget-feature=+avx2",
    "-Ctarget-feature=+fma",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
