[build]
target = "x86_64-unknown-none.json"

rustflags = [
    "-C", "link-args=-image-base=0x1400000",
    "-C", "relocation-model=static",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
