[build]
target = "i586-unknown-none.json"

[target.i586-unknown-none]
rustflags = [
    "-C", "link-args=-image-base=0x8000",
    "-C", "relocation-model=static",
    "-C", "link-args=../build/bootloader/low_level.o",
]

[unstable]
build-std = ["core", "compiler_builtins"]
