[package]
name = "bootloader"
version = "0.1.0"
authors = ["addrianyy <adrianvpl@gmail.com>"]
edition = "2018"

[dependencies]
libc_routines = { path = "../libs/libc_routines" }

[build-dependencies]
asmlink = { path = "../libs/asmlink" }
